from resources import *
from home import *

def create_Psyduck(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		PSYDUCK_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(PSYDUCK_IMG_01, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_02, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_03, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_04, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_05, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_06, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_07, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_08, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_09, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_10, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_11, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_12, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_13, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_14, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_15, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_16, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_17, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_18, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_19, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_20, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_21, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_22, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_23, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_24, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PSYDUCK_IMG_25, "PSYDUCK", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Squirtle(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		SQUIRTLE_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(SQUIRTLE_IMG_01, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_01, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_01, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_01, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_01, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_02, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_02, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_02, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_02, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_02, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_03, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_03, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_03, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_03, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_03, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_04, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_04, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_04, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_04, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_04, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_04, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_05, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_05, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_05, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_05, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_06, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_06, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_06, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_06, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_06, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_07, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_07, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_07, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_07, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_07, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_08, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_08, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_08, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_08, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_08, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_09, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_09, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_09, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_09, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_09, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_10, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_10, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_10, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_10, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_10, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_11, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_11, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_11, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_11, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_11, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_12, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_12, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_12, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_12, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_12, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_13, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_13, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_13, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_13, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_13, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_14, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_14, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_14, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_14, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_14, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_15, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_15, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_15, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_15, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_15, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_16, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_16, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_16, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_16, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_16, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_17, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_17, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_17, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_17, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_17, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_18, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_18, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_18, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_18, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_18, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_19, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_19, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_19, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_19, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_19, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_20, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_20, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_20, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_20, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_20, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_21, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_21, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_21, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_21, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_21, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_22, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_22, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_22, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_22, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_22, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_23, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_23, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_23, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_23, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_23, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_24, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_24, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_24, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_24, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_24, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_25, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_25, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_25, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_25, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_25, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_26, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_26, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_26, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_26, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_26, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_27, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_27, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_27, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_27, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_27, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_28, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_28, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_28, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_28, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_28, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_29, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_29, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_29, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_29, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_29, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_30, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_30, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_30, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_30, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_30, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SQUIRTLE_IMG_31, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_31, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_31, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_31, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_31, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 

	clock.tick(15)
	create_area(SQUIRTLE_IMG_32, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_32, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_32, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_32, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SQUIRTLE_IMG_32, "SQUIRTLE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Pikachu (sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		PIKACHU_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(PIKACHU_IMG_1, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_2, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_3, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_4, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_5, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_6, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_7, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_8, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_9, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_10, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_11, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_12, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_13, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_14, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_15, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_16, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(PIKACHU_IMG_17, "PIKACHU", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	

def create_Eevee(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		EEVEE_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(EEVEE_IMG_01, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_02, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_03, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_04, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_05, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_06, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_07, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_08, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_09, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_10, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_11, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_12, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_13, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_14, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_15, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_16, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_17, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_18, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_19, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(EEVEE_IMG_20, "EEVEE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 

def create_Bulbasaur(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :


	# Pokemon Sound

	if sound == 0:
		BULBASAUR_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(BULBASAUR_IMG_01, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_02, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_03, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_04, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_05, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_06, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_07, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_08, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_09, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_10, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_11, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_12, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_13, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_14, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_15, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_16, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_17, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_18, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_19, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_20, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_21, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_22, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_23, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_24, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_25, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_26, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_27, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_28, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_29, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_30, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_31, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_32, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_33, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_34, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_35, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_36, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_37, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_38, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_39, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_40, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_41, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_42, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_43, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_44, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_45, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_46, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_47, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_48, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_49, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_50, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_51, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BULBASAUR_IMG_52, "BULBASAUR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Charmander(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		CHARMANDER_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(CHARMANDER_IMG_01, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_02, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_03, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_04, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_05, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_06, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_07, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_08, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_09, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_10, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_11, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_12, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_13, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_14, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_15, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_16, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_17, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_18, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_19, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_20, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_21, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_22, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_23, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_24, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_25, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_26, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_27, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_28, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_29, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_30, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_31, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_32, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_33, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_34, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_35, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_36, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_37, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_38, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_39, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_40, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_41, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_42, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_43, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_44, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_45, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_46, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_47, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_48, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_49, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_50, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_51, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_52, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_53, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(CHARMANDER_IMG_54, "CHARMANDER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_MrMime(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		MRMIME_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(MRMIME_IMG_01, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_02, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_03, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_04, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_05, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_06, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_07, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_08, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_09, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_10, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_11, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_12, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_13, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_14, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_15, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_16, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_17, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MRMIME_IMG_18, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)
	clock.tick(15)
	create_area(MRMIME_IMG_19, "MR. MIME", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Arcanine(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		ARCANINE_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(ARCANINE_IMG_01, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_02, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_03, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_04, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_05, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_06, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_07, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_08, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_09, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_10, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_11, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_12, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_13, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_14, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_15, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_16, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_17, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(ARCANINE_IMG_18, "ARCANINE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Growlithe(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		GROWLITHE_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(GROWLITHE_IMG_01, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_02, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_03, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_04, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_05, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_06, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_07, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_08, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_09, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_10, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_11, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_12, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_13, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_14, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_15, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_16, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_17, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GROWLITHE_IMG_18, "GROWLITHE", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Gastly(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		GASTLY_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(GASTLY_IMG_01, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_02, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_03, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_04, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_05, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_06, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_07, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_08, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_09, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_10, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_11, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_12, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_13, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_14, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_15, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_16, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GASTLY_IMG_17, "GASTLY", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 

def create_Meowth(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		MEOWTH_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(MEOWTH_IMG_01, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_02, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_03, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_04, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_05, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_06, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_07, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_08, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_09, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_10, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_11, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_12, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_13, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_14, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_15, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_16, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_17, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_18, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_19, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_20, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_21, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_22, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_23, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(MEOWTH_IMG_24, "MEOWTH", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Beedrill(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		BEEDRILL_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(BEEDRILL_IMG_01, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_02, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_03, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_04, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_05, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_06, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_07, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_08, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_09, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_10, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_11, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_12, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_13, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_14, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_15, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_16, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_17, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_18, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_19, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_20, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_21, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_22, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(BEEDRILL_IMG_23, "BEEDRILL", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Scyther(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		SCYTHER_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_01, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_02, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_03, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_04, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_05, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_06, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_07, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	create_area(SCYTHER_IMG_08, "SCYTHER", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	

def create_Gengar(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		GENGAR_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(GENGAR_IMG_01, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_02, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_03, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_04, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_05, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_06, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_07, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_08, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_09, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_10, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_11, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_12, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_13, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_14, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_15, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_16, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_17, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_18, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_19, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(GENGAR_IMG_20, "GENGAR", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


def create_Umbreon(sound, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs)  :

	# Pokemon Sound

	if sound == 0:
		UMBREON_SOUND.play()
		sound +=1

	# Pokemon Sprites

	create_area(UMBREON_IMG_02, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_03, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_04, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_05, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_06, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_07, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_08, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_09, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_11, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_12, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_13, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_14, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_15, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_16, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_17, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_18, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_19, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_20, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_21, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_22, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_23, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_24, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_25, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_26, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_27, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_28, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_29, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_30, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_31, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_32, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_33, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 
	clock.tick(15)
	create_area(UMBREON_IMG_34, "UMBREON", variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) 


# ---------------------------- Shared libs -----------------------------



def create_area (POKEMON, POKEMON_NAME, variableHP, staticHP, pokemonStaticHP, pokemonVariableHP, randomLevel, pokemonLevel, trainer_pokeballs) :

	now = datetime.now()
	hora = now.strftime("%H")

	if hora <="16" and hora >="10" :
		WIN.blit(BATTLE_ARENA_IMG, (0,0))

	elif hora >="17" and hora <"20":
		WIN.blit(BATTLE_ARENA_NIGHT_IMG, (0,0)) # Place background image

	else:
		WIN.blit(BATTLE_ARENA_NIGHT_IMG, (0,0))


	# Battle Elements
	#WIN.blit(PIKACHU_BATTLE_IMG, (0,250))
	WIN.blit(POKEMON, (640,160))
	WIN.blit(BATTLE_MENU, (600,410)) # Place background image
	WIN.blit(CURSOR, (cursor_pos.x, cursor_pos.y))
	WIN.blit(LIFE_MENU, (680, 30))
	WIN.blit(LIFE_MENU, (0, 30))

	wild = RULES.render("" + str(POKEMON_NAME), 1, BLACK)
	WIN.blit(wild, (685, 35))

	level = RULES.render("Lv " + str(randomLevel), 1, BLACK)
	WIN.blit(level, (840, 35))

	stats = RULES.render("" + str(variableHP), 1, BLACK)
	WIN.blit(stats, (692, 60))

	separator = RULES.render("/", 1, BLACK)
	WIN.blit(separator, (710, 60))

	stats = RULES.render("" + str(staticHP) , 1, BLACK)
	WIN.blit(stats, (720, 60))

	if variables["TRAINER"]["POKEMON_1"]["HP"] > 0 :

		WIN.blit(PIKACHU_BATTLE_IMG, (0,250))

		friend = RULES.render("" + str("PIKACHU"), 1, BLACK)
		WIN.blit(friend, (5, 35))

		stats = RULES.render("" + str(pokemonVariableHP) , 1, BLACK)
		WIN.blit(stats, (12, 60))

		separator = RULES.render("/", 1, BLACK)
		WIN.blit(separator, (30, 60))

		stats = RULES.render("" + str(pokemonStaticHP), 1, BLACK)
		WIN.blit(stats, (40, 60))


		level = RULES.render("Lv " + str(pokemonLevel), 1, BLACK)
		WIN.blit(level, (160, 35))

	elif variables["TRAINER"]["POKEMON_1"]["HP"] == 0 :
		if variables["TRAINER"]["POKEMON_2"]["HP"] > 0 :

			if variables["TRAINER"]["POKEMON_2"]["NAME"] == "SQUIRTLE":
				WIN.blit(SQUIRTLE_BATTLE_IMG, (0,250))

			elif variables["TRAINER"]["POKEMON_2"]["NAME"] == "CHARMANDER":
					WIN.blit(CHARMANDER_BATTLE_IMG, (0,250))

			elif variables["TRAINER"]["POKEMON_2"]["NAME"] == "BULBASAUR":
					WIN.blit(BULBASAUR_BATTLE_IMG, (0,250))


			friend = RULES.render("" + str(variables["TRAINER"]["POKEMON_2"]["NAME"]), 1, BLACK)
			WIN.blit(friend, (5, 35))

			stats = RULES.render("" + str(pokemonVariableHP) , 1, BLACK)
			WIN.blit(stats, (12, 60))

			separator = RULES.render("/", 1, BLACK)
			WIN.blit(separator, (30, 60))

			stats = RULES.render("" + str(pokemonStaticHP), 1, BLACK)
			WIN.blit(stats, (40, 60))


			level = RULES.render("Lv " + str(variables["TRAINER"]["POKEMON_2"]["LEVEL"]), 1, BLACK)
			WIN.blit(level, (160, 35))

		elif variables["TRAINER"]["POKEMON_1"]["HP"] == 0 and variables["TRAINER"]["POKEMON_2"]["HP"] == 0 :
			if variables["TRAINER"]["POKEMON_3"]["HP"] > 0 :

				if variables["TRAINER"]["POKEMON_3"]["NAME"] == "SQUIRTLE":
					WIN.blit(SQUIRTLE_BATTLE_IMG, (0,250))

				elif variables["TRAINER"]["POKEMON_3"]["NAME"] == "CHARMANDER":
						WIN.blit(CHARMANDER_BATTLE_IMG, (0,250))

				elif variables["TRAINER"]["POKEMON_3"]["NAME"] == "BULBASAUR":
						WIN.blit(BULBASAUR_BATTLE_IMG, (0,250))


				friend = RULES.render("" + str(variables["TRAINER"]["POKEMON_3"]["NAME"]), 1, BLACK)
				WIN.blit(friend, (5, 35))

				stats = RULES.render("" + str(pokemonVariableHP) , 1, BLACK)
				WIN.blit(stats, (12, 60))

				separator = RULES.render("/", 1, BLACK)
				WIN.blit(separator, (30, 60))

				stats = RULES.render("" + str(pokemonStaticHP), 1, BLACK)
				WIN.blit(stats, (40, 60))


				level = RULES.render("Lv " + str(variables["TRAINER"]["POKEMON_3"]["LEVEL"]), 1, BLACK)
				WIN.blit(level, (160, 35))


	pygame.display.update()
